import { setRequestLocale } from 'next-intl/server';

export default async function TermsPage({ params }: { params: Promise<{ locale: string }> }) {
  const { locale } = await params;
  setRequestLocale(locale);

  return (
    <div className="mx-auto max-w-2xl px-4 py-12">
      <h1 className="mb-8 text-3xl font-bold">Terms of Service</h1>
      <p className="mb-4 text-sm text-gray-400">Last updated: February 16, 2026</p>

      <div className="space-y-6 text-gray-300 leading-relaxed">
        <section>
          <h2 className="mb-2 text-xl font-semibold text-white">1. Service Overview</h2>
          <p>SleepGuard is an AI-powered sleep coaching application. Luna, the AI coach, provides conversational support to help users improve their sleep habits. SleepGuard is not a medical device and does not provide medical advice.</p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-white">2. Account</h2>
          <p>You must provide a valid email address to create an account. You are responsible for maintaining the security of your account credentials.</p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-white">3. Free & Premium Plans</h2>
          <ul className="ml-4 list-disc space-y-1">
            <li><strong>Free:</strong> Up to 3 AI conversations per night, 2 coach personalities, weekly statistics.</li>
            <li><strong>Premium ($6.99 one-time):</strong> Unlimited AI conversations, 4 coach personalities, monthly statistics & trends, full achievement badges, sleep sounds.</li>
          </ul>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-white">4. Payment</h2>
          <p>Premium purchases are processed securely by Stripe. The $6.99 payment is a one-time charge granting lifetime access to premium features. No recurring billing.</p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-white">5. AI Disclaimer</h2>
          <p>Luna&apos;s responses are generated by AI (Anthropic Claude). While designed to be helpful, the advice is general in nature. SleepGuard is not a substitute for professional medical or psychological advice. If you have a sleep disorder, please consult a healthcare professional.</p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-white">6. Prohibited Use</h2>
          <p>You may not use SleepGuard to attempt to extract harmful content from the AI, reverse-engineer the service, or violate any applicable laws.</p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-white">7. Termination</h2>
          <p>We reserve the right to suspend or terminate accounts that violate these terms. You may delete your account at any time.</p>
        </section>

        <section>
          <h2 className="mb-2 text-xl font-semibold text-white">8. Contact</h2>
          <p>Questions about these terms: <a href="mailto:koh923@icloud.com" className="text-luna-purple hover:underline">koh923@icloud.com</a></p>
        </section>
      </div>
    </div>
  );
}
